feat: Add minimum first deposit, refactor convert/preview functions (SC-446)
sparkdotfi/spark-psm pull request #2
Opened 2024-05-21 17:06 UTC by lucas-manuel

## Share Inflation Attack Initial Approach vs. Final Approach
This PR was originally created to address the issue outlined in picture below **within the contract's `deposit` logic**. This was fully implemented in [commit d32fd2f](https://github.com/marsfoundation/spark-psm/pull/2/commits/d32fd2faf5d3d255075f4eef9d6639f1118f5eb3). It was subsequently removed in favor of simplifying core logic in the contract and addressing the issue in a different way - by operationally requiring an initial deposit to be made on deployment. This would fix multiple attack vectors as outlined in @hexonaut's [comment](https://github.com/marsfoundation/spark-psm/pull/2#pullrequestreview-2085880206).

![Screenshot 2024-05-16 at 3 51 13 PM](https://github.com/marsfoundation/spark-psm/assets/44272939/3b9943fc-7337-464e-96de-31022d462070)

## Other Changes within PR

- Adds test to prove that the attack vector is resolved by the initial deposit being made.
- Adds section to README outlining attack prevention measures to be taken.
- Also refactors to use `preview` functions to return rounding-accurate conversions.
- Updates to have convertToShares and convertToAssets use generic value and asset-specific values.

2024-05-31 20:00 UTC, hexonaut requested changes
Mostly looks good. Some requested changes.

I would also make the recommendation to burn at least 1 full unit instead of 1000 shares.

2024-06-01 16:19 UTC, lucas-manuel commented on src/PSM.sol
>          if (sharesToBurn > shares[msg.sender]) {
Updated

2024-06-01 16:19 UTC, lucas-manuel commented on src/PSM.sol
> +    function previewDeposit(address asset, uint256 assets) public view returns (uint256) {
Updated

2024-06-01 16:22 UTC, lucas-manuel commented on src/PSM.sol
> +        result_ = (numerator_ + divisor_ - 1) / divisor_;
Updated

2024-06-04 06:23 UTC, hexonaut approved these changes
Good to merge now.

2024-06-04 12:22 UTC, merged